"""add code model

Revision ID: 04dc85ee0154
Revises: 9e8049f715b4
Create Date: 2022-04-29 20:37:00.492610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04dc85ee0154'
down_revision = '9e8049f715b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verification_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(), nullable=True),
    sa.Column('code', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['users.email'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_verification_code_id'), 'verification_code', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verification_code_id'), table_name='verification_code')
    op.drop_table('verification_code')
    # ### end Alembic commands ###
