"""update models

Revision ID: 5ba092491e82
Revises: 90a7c5bf994f
Create Date: 2022-04-30 05:19:45.853423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ba092491e82'
down_revision = '90a7c5bf994f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('districts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('districts', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('districts')
    )
    op.create_index(op.f('ix_districts_id'), 'districts', ['id'], unique=True)
    op.add_column('bid', sa.Column('district', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'bid', 'districts', ['district'], ['districts'])
    op.add_column('users', sa.Column('district', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'users', 'districts', ['district'], ['districts'])
    op.drop_column('users', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('address', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'district')
    op.drop_constraint(None, 'bid', type_='foreignkey')
    op.drop_column('bid', 'district')
    op.drop_index(op.f('ix_districts_id'), table_name='districts')
    op.drop_table('districts')
    # ### end Alembic commands ###
