"""add in bid model code

Revision ID: 75dad8386629
Revises: 4d96168b58b1
Create Date: 2022-04-30 03:34:29.211107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75dad8386629'
down_revision = '4d96168b58b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bid', sa.Column('code', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'bid', ['code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bid', type_='unique')
    op.drop_column('bid', 'code')
    # ### end Alembic commands ###
