"""update bid model

Revision ID: 90a7c5bf994f
Revises: 75dad8386629
Create Date: 2022-04-30 03:36:25.425512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90a7c5bf994f'
down_revision = '75dad8386629'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bid', 'city',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('bid', 'code',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bid', 'address_delivery',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('bid', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('bid', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('bid', 'middle_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('bid', 'number',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('bid', 'address_live',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('bid', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('bid', 'image_1',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('bid', 'image_2',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('bid', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bid', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('bid', 'image_2',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('bid', 'image_1',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('bid', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('bid', 'address_live',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('bid', 'number',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('bid', 'middle_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('bid', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('bid', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('bid', 'address_delivery',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('bid', 'code',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('bid', 'city',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
