"""all

Revision ID: f76720ac9c89
Revises: a15aabc84be1
Create Date: 2022-04-30 06:58:49.831489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f76720ac9c89'
down_revision = 'a15aabc84be1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
